language: ruby
sudo: false 
dist: xenial
rvm:
  - 2.4.1
warnings_are_errors: false

notifications:
  email:
    recipients:
      - s.vissault@yahoo.fr

before_install:
  - sudo apt-get install -y lftp

install: gem install jekyll jekyll-sitemap jekyll-scholar

script: jekyll build

cache: bundler # caching bundler gem packages will speed up build

after_success:
  - cp _site/home/index.html _site/index.html
  - chmod +x script/deploy.sh
  - bash script/deploy.sh