# Site settings
title: Integrative ecology Lab
email: dominique.gravel@usherbrooke.ca
description: "Integrative Ecology Research laboratory led by Dominique Gravel at Sherbrooke University"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ielab.recherche.usherbrooke.ca/" # the base hostname & protocol for your site
twitter_username: SVissault
github_username:  SteveViss
keys: [Dominique Gravel,Integrative,computational,theoretical,ecology,modelisation,networks,forest,climate change,global warming]

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

scholar:
  style: assets/csl/ecology.csl
  locale: en
  repository: assets/pdf
  sort_by: year
  order: reverse

  source: _bibliography
  bibliography: labo.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  bibliography_list_tag: p
  bibliography_item_tag: p

  query: "@*"
